name: Pre-Commit CI Check
# 触发条件：推送到主分支、PR到主分支
on:
  push:
    branches: [ main, master ]
    paths:
      - '**.h'
      - '**.hh'
      - '**.hxx'
      - '**.hpp'
      - '**.c'
      - '**.cc'
      - '**.cpp'
      - '**.cxx'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.rst'
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '.pre-commit-config.yaml'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.h'
      - '**.hh'
      - '**.hxx'
      - '**.hpp'
      - '**.c'
      - '**.cc'
      - '**.cpp'
      - '**.cxx'
      - 'CMakeLists.txt'
      - '**.cmake'
      - '**.rst'
      - '**.yml'
      - '**.yaml'
      - '**.json'
      - '.pre-commit-config.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit-check:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 修复点：移除 cache: 'pip'，避免因缺少依赖文件报错
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 仅保留Python版本，不启用pip缓存

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Cache pre-commit dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
